### ISSUE TITLE
DNS lookup exception for openfire

### ISSUE THREAD

**Issue by kosaa** [smartinrub/spring-xmpp-websocket-reactjs#7]
Just default project setup. I have created a user and after Login click i get following error from XMPPClient.java at line 61.

env:
OSX 12.3.1

```
org.jivesoftware.smack.SmackException$EndpointConnectionException: Could not lookup the following endpoints: RemoteConnectionEndpointLookupFailure(description='DNS lookup exception for openfire' exception='java.net.UnknownHostException: openfire: nodename nor servname provided, or not known')
	at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334) ~[smack-core-4.4.6.jar:4.4.6]
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:664) ~[smack-tcp-4.4.6.jar:4.4.6]
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:849) ~[smack-tcp-4.4.6.jar:4.4.6]
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:526) ~[smack-core-4.4.6.jar:4.4.6]
	at com.sergiomartinrubio.springxmppwebsocketsecurity.xmpp.XMPPClient.connect(XMPPClient.java:61) ~[classes/:na]
	at com.sergiomartinrubio.springxmppwebsocketsecurity.facade.XMPPFacade.startSession(XMPPFacade.java:55) ~[classes/:na]
	at com.sergiomartinrubio.springxmppwebsocketsecurity.websocket.ChatWebSocket.open(ChatWebSocket.java:31) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.apache.tomcat.websocket.pojo.PojoEndpointBase.doOnOpen(PojoEndpointBase.java:69) ~[tomcat-embed-websocket-9.0.65.jar:9.0.65]
	at org.apache.tomcat.websocket.pojo.PojoEndpointServer.onOpen(PojoEndpointServer.java:48) ~[tomcat-embed-websocket-9.0.65.jar:9.0.65]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:136) ~[tomcat-embed-websocket-9.0.65.jar:9.0.65]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:933) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.65.jar:9.0.65]
	at java.base/java.lang.Thread.run(Thread.java:883) ~[na:na]
```

**Comment by smartinrub** [comment]
I replaced the Openfire docker image with `nasqueron/openfire` and fixed the npm start script. I don't see errors anymore and it should work for you too.

However the issue you mentioned seems to be a misconfiguration. Are you running the 
containerized Openfire? Remember,`xmpp.host` on the `application.properties` must point to your Openfire instance. If Openfire is not running as part of the `docker-compose` file, you might need to use `localhost`.
